### ISSUE TITLE
Trouble with domain.forward.update

### ISSUE THREAD

**Issue by marshallmassengill** [veilleperso/gandi#13]
I'm having some issues with implementing domain.forward.update.  I'm getting this error.

/var/lib/gems/1.9.1/gems/gandi-2.1.2/lib/gandi/session.rb:187:in `rescue in method_missing': Error on object : OBJECT_UNKNOWN (CAUSE_BADPARAMETER) [invalid method parameter(s)] (Gandi::DataError)

My call looks like this:
api.domain.forward.update(domainName,source,destinations)

I suspect it has something to do with the way destinations is formatted but it is just an array of strings.

Any ideas?  Is this a bug or am I just doing something wrong?

Thanks for the help!

**Comment by veilleperso** [comment]
No idea about what you are doing wrong but it's probably some wrong parameters. The best is to look at the API doc, as this gem is only a wrapper around the API. For all gandi API syntax, you must look at their documentation

**Comment by marshallmassengill** [comment]
After going back and forth with this for a while, it seems to be something in the gem.  I switched over to just using calls from the API spec and that seems to work.  I tried just about every format I could think of and still had no luck with this call and this gem.

**Comment by veilleperso** [comment]
Ok, me I don't have any problem with this method or gem, by calling something like this in one of my apps in production:
api.domain.forward.update(name, source, {destinations: [email]})

Cf. http://doc.rpc.gandi.net/domain/reference.html#domain.forward.update
and
http://doc.rpc.gandi.net/domain/reference.html#ForwardDescription
The format of parameters is will documented in the gandi spec, and if you stick to it, you should not have any problem.

How to you do your call exactly? Ie can you provide a code sample that you use to see whats wrong?

**Comment by marshallmassengill** [comment]
Here is what ended up finally working for me:

destinationHash = {'destinations' => destinations}
server.call("domain.forward.update", apikey, domainName, item,
destinationHash)

Destinations is just an array of email addreseses.  I'm not sure I can
explain it myself either.  I looked at the gem for a bit and did my best to
try and figure it out but I couldn't.  Unfortunately I don't have the code
I was using but I can attempt to recreate it if it's worth it for you.

Thanks for looking into it.  It's entirely possible it is something on my
end... I've been running this on a Raspberry Pi with ubuntu if that helps
too.

---Marshall
